# Generated by Django 5.0.6 on 2024-07-03 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_room_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
